name: deps

on:
  push:
    branches: [master, main]
  pull_request:
  schedule:
    - cron: "0 6 * * 1"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  audit:
    uses: guinea-rs/.github/.github/workflows/deps-audit.yml@02c22ffa63298c80099e037effd27005e0e78939
    with:
      manifests: '["Cargo.toml", "examples/dioxus/Cargo.toml", "examples/egui/Cargo.toml", "examples/gpui/Cargo.toml", "examples/iced/Cargo.toml", "examples/ratatui/Cargo.toml", "examples/slint/Cargo.toml", "examples/tauri-leptos/Cargo.toml", "examples/tauri-typescript/src-tauri/Cargo.toml", "examples/tauri-yew/Cargo.toml", "examples/web-dioxus/Cargo.toml", "examples/web-leptos/Cargo.toml", "examples/web-yew/Cargo.toml"]'

  tags:
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    permissions:
      contents: read
      issues: write
    uses: guinea-rs/.github/.github/workflows/deps-tags.yml@02c22ffa63298c80099e037effd27005e0e78939
    with:
      manifests: '["Cargo.toml", "examples/dioxus/Cargo.toml", "examples/egui/Cargo.toml", "examples/gpui/Cargo.toml", "examples/iced/Cargo.toml", "examples/ratatui/Cargo.toml", "examples/slint/Cargo.toml", "examples/tauri-leptos/Cargo.toml", "examples/tauri-typescript/src-tauri/Cargo.toml", "examples/tauri-yew/Cargo.toml", "examples/web-dioxus/Cargo.toml", "examples/web-leptos/Cargo.toml", "examples/web-yew/Cargo.toml"]'
